CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(200),
    content TEXT,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);